//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Invoiceds = new HashSet<Invoiced>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        [DataMember]
        public int OrderID { get; set; }

        [DataMember]
        public int CustomerID { get; set; }

        [DataMember]
        public int AddressID { get; set; }

        [DataMember]
        public System.DateTime OrderDate { get; set; }

        [DataMember]
        public bool Complete { get; set; }

        [DataMember]
        public Address Address { get; set; }

        [DataMember]
        public Customer Customer { get; set; }

        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<Invoiced> Invoiceds { get; set; }

        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
