//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        [DataMember]
        public int ProductID { get; set; }

        [DataMember]
        public int RetailerID { get; set; }

        [DataMember]
        public int SubCategoryID { get; set; }

        [DataMember]
        public string ProductName { get; set; }

        [DataMember]
        public string ProductDescription { get; set; }

        [DataMember]
        public decimal Price { get; set; }

        [DataMember]
        public int UnitsInStock { get; set; }

        [DataMember]
        public byte[] Picture { get; set; }

        [DataMember]
        public Nullable<bool> IsDiscontinued { get; set; }

        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<OrderDetail> OrderDetails { get; set; }

        [DataMember]
        public ProductSubCategory ProductSubCategory { get; set; }

        [DataMember]
        public Retailer Retailer { get; set; }
    }
}
